input {
  beats {
    port => 5044
  }
}

filter {
  # 第四周补充解析规则
}

output {
  elasticsearch {
    hosts => ["learn-es:9200"]
    index => "learn-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
